### ISSUE TITLE
demo 代码报错

### ISSUE THREAD

**Issue by mrme2014** [YummyLau/Anchors#1]
```

       Project.Builder builder1 = new Project.Builder(PROJECT_1, testTaskFactory);
        builder1.add(TASK_10);
        builder1.add(TASK_11).dependOn(TASK_10);
        builder1.add(TASK_12).dependOn(TASK_11);
        builder1.add(TASK_13).dependOn(TASK_12);
        Project project1 = builder1.build();

        AnchorsManager.getInstance().debuggable(true)
                .addAnchors(TASK_10)
                .start(project1);
```
  `start()`方法如果传入的是project对象。那么运行起来会有报空指针,日志如下：
```
Attempt to invoke virtual method 'android.util.SparseArray com.effective.android.anchors.TaskRuntimeInfo.getStateTime()' on a null object reference
        at com.effective.android.anchors.LogTaskListener.logTaskRuntimeInfoString(LogTaskListener.java:28)
        at com.effective.android.anchors.LogTaskListener.onFinish(LogTaskListener.java:23)
        at com.effective.android.anchors.Task.toFinish(Task.java:140)
        at com.effective.android.anchors.Task.run(Task.java:101)
```

**Comment by YummyLau** [comment]
目前不支持传递project做为节点，跟节点需要传递一个自己实现的task类。
这部分已经优化了。你可以构建一个在project前面的空节点解决。
一般project对应一个聚合的task群。例子可以参考TaskTest。

**Comment by YummyLau** [comment]
> ```
> 
>        Project.Builder builder1 = new Project.Builder(PROJECT_1, testTaskFactory);
>         builder1.add(TASK_10);
>         builder1.add(TASK_11).dependOn(TASK_10);
>         builder1.add(TASK_12).dependOn(TASK_11);
>         builder1.add(TASK_13).dependOn(TASK_12);
>         Project project1 = builder1.build();
> 
>         AnchorsManager.getInstance().debuggable(true)
>                 .addAnchors(TASK_10)
>                 .start(project1);
> ```
> 
> `start()`方法如果传入的是project对象。那么运行起来会有报空指针,日志如下：
> 
> ```
> Attempt to invoke virtual method 'android.util.SparseArray com.effective.android.anchors.TaskRuntimeInfo.getStateTime()' on a null object reference
>         at com.effective.android.anchors.LogTaskListener.logTaskRuntimeInfoString(LogTaskListener.java:28)
>         at com.effective.android.anchors.LogTaskListener.onFinish(LogTaskListener.java:23)
>         at com.effective.android.anchors.Task.toFinish(Task.java:140)
>         at com.effective.android.anchors.Task.run(Task.java:101)
> ```
目前不支持传递project做为根节点。
start参数里面写传递Task对象不够严谨，在设计的时候想约束下project。
感谢提示。可以构建一个task对象进行处理，可以参考TaskTest。
已经优化了，后续发版

**Comment by mrme2014** [comment]
老哥，赶快更新吧。这个项目还是不错滴。我也看了alpha的代码。着实有点鸡肋

**Comment by YummyLau** [comment]
> 老哥，赶快更新吧。这个项目还是不错滴。我也看了alpha的代码。着实有点鸡肋

ok的

**Comment by YummyLau** [comment]
@mrme2014 已经发布1.0.2
