### ISSUE TITLE
组件化中使用 报has no any anchor！

### ISSUE THREAD

**Issue by i91h1r** [YummyLau/Anchors#11]
在lib _common 公共库中集成Anchors 并且在baseApplication 中初始化，然后再别的module 中引用lib _common，无法初始化，比如将ARouter 得初始化直接写在baseApplication 中就能正常初始化

**Comment by YummyLau** [comment]
@hyr0318 has no any anchor 是一个warning 级别的提示，和初始化流程没有关系。 Anchors框架下如果你的初始化流程不需要设置 anchor 锚点用于等待也是可以用的。
