### ISSUE TITLE
Task启动时是否可以不依赖project或者不依赖TaskFactory

### ISSUE THREAD

**Issue by Dwan-xie** [YummyLau/Anchors#16]
Task启动时是否可以不依赖project或者不依赖TaskFactory

**Comment by YummyLau** [comment]
@Dwan-xie  Task可以独立。依赖TaskFactory只是构建project方便而已，project也是一个task

**Comment by Dwan-xie** [comment]
我试了task直接dependOn，可以正常执行后学task。
