### ISSUE TITLE
请问一定要形成图吗？

### ISSUE THREAD

**Issue by xuciluan** [YummyLau/Anchors#17]
不可以有一些任务是单独运行的，有一些是有依赖关系的吗？
单看API感觉是一定要有依赖关系，感觉有点强迫了。
个人感觉，API设计的有些复杂了，不是很容易上手。

**Comment by YummyLau** [comment]
@xuciluan 项目需要图起手。当然，哪怕是独立的，分散的，万物皆可构成图（可以依赖一些辅助节点）
