### ISSUE TITLE
请求更新一份用法讲解的文档

### ISSUE THREAD

**Issue by InnocentYang** [YummyLau/Anchors#19]
Hi~~我下载了Demo想试着加到自己的项目里，发现Anchors库的用法有些看不懂。
比如 getInstance().taskFactory { TestTaskFactory() }.anchors { arrayOf(TASK_93, "TASK_E", TASK_10) }
的anchors是做什么用的呢？
追踪代码发现它在AnchorsManager.startUp()中把anchors: MutableList<String>添加到了AnchorsManager.anchorTaskIds: MutableSet<String>中，除了有一处clear()，都没有从列表中取出过，
那要它干什么呢？

还有相比alpha库的新功能Application.onCreate()能卡住等待初始化完成，我也没搞懂怎么用。

希望您能更新一下用法讲解文档。

**Comment by YummyLau** [comment]
anchors 对应的节点，就是用来保证application前初始化的。
只有kotlin dsl 使用图构造依赖才会使用 startUp 初始化。
如果你是kotlin，只需要看kotlin用法，java看java用法就好。

**Comment by dwdegithub** [comment]
看了半天不知道怎么用。写了怎么多，用法写的也太随意了

**Comment by YummyLau** [comment]
> 看了半天不知道怎么用。写了怎么多，用法写的也太随意了
你是觉得哪里随意了呢？

**Comment by YummyLau** [comment]
> 看了半天不知道怎么用。写了怎么多，用法写的也太随意了

你是觉得哪里随意了呢？

**Comment by YummyLau** [comment]
@InnocentYang  @dwdegithub 更新了readme及demo严格区分java/kotlin，有对应的类可以按需查看。
