### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference

### ISSUE THREAD

**Issue by Doikki** [YummyLau/Anchors#27]
java.lang.RuntimeException:Unable to create application com.stub.StubApp: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:6637)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
6 com.effective.android.anchors.e.g(AnchorsRuntime.kt:87)
7 com.effective.android.anchors.b.b(AnchorsManager.kt:118)
8 com.effective.android.anchors.d.a(AnchorsManager.kt:291)
9 com.xxx.xxx.managers.l.b(LaunchManager.kt:142)
10 com.xxx.xxx.managers.l.a(LaunchManager.kt:93)
11 com.xxx.xxx.app.MyApplication.onCreate(MyApplication.java:97)
12 com.stub.StubApp.onCreate(SourceFile:118)
13 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
14 android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
15 android.app.ActivityThread.-wrap2(Unknown Source:0)
16 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
17 android.os.Handler.dispatchMessage(Handler.java:108)
18 android.os.Looper.loop(Looper.java:166)
19 android.app.ActivityThread.main(ActivityThread.java:7529)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by YummyLau** [comment]
@Doikki 提供下你的链调用场景和写法，需要排除下业务是否主动清除队列的逻辑。

**Comment by Doikki** [comment]
AnchorsManager.getInstance()
                .debuggable { EnvironmentManager.getInstance().isApkDebug }
                .taskFactory { Project.TaskFactory(GDTaskCreator) }
                .anchors { //必须在 Application onCreate 结束之前启动完成的任务
                    arrayOf(
                            ACCOUNT,
                            PHOTO_EDIT,
                            J_VERIFICATION
                    )
                }
                .graphics { //启动任务列表
                    arrayOf(
                            ACCOUNT.sons(
                                    NETWORK_STATE,
                                    NPS,
                                    USER_INFO
                            ),
                            CACHE,
                            PHOTO_EDIT,
                            J_VERIFICATION,
                            DOOR,
                            BUGLY,
                            UMENG
                    )
                }
                .startUp()

**Comment by Doikki** [comment]
#26 这个问题我这也出现过

**Comment by Doikki** [comment]
object GDTaskCreator : TaskCreator {
    override fun createTask(taskName: String): Task {
        return when (taskName) {
            LaunchManager.BUGLY -> BuglyTask()
            LaunchManager.PHOTO_EDIT -> PhotoEditTask()
            LaunchManager.DOOR -> DoorTask()
            LaunchManager.ACCOUNT -> AccountTask()
            LaunchManager.NPS -> NPSTask()
            LaunchManager.CACHE -> CacheTask()
            LaunchManager.USER_INFO -> UserInfoTask()
            LaunchManager.J_VERIFICATION -> JVerificationTask()
            LaunchManager.UMENG -> UmengTask()
            LaunchManager.NETWORK_STATE -> NetworkStateTask()
            else -> EmptyTask
        }
    }
}

**Comment by Doikki** [comment]
老哥有啥想法吗

**Comment by Doikki** [comment]
runBlockTask会被子线程访问，你没线程同步

**Comment by YummyLau** [comment]
@Doikki 你的业务代码有触动调用框架的某些流程或者修改某些变量么。还是说仅仅只有 startUp。

**Comment by YummyLau** [comment]
无活跃暂时关闭，有问题可打开。
