### ISSUE TITLE
是否有提供类似alpha的onProjectFinish的回调

### ISSUE THREAD

**Issue by yangfanCode** [YummyLau/Anchors#28]
是否有提供类似alpha的onProjectFinish的回调而不是每个task完成的回调，比如在整个初始化做完之后需要做一些事情的时候

**Comment by yangfanCode** [comment]
kotlin的dsl方式

**Comment by YummyLau** [comment]
@yangfanCode 目前project也是一个task，可以当作task进行监听的。  kotlin dsl 目前提供的是更方便创建方式。
