### ISSUE TITLE
组件化

### ISSUE THREAD

**Issue by jiangsai** [YummyLau/Anchors#29]
能不能每个组件初始化自己的，然后app启动的时候把所有组件的初始化整合一起重新排列去选择最优的初始化方式

**Comment by YummyLau** [comment]
@jiangsai 当然可以，这个是编程的方式，库是支持的。

**Comment by jiangsai** [comment]
组件化要怎么用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YummyLau/Anchors] 组件化 (#29)




 
@jiangsai 当然可以，这个是编程的方式，库是支持的。

**Comment by YummyLau** [comment]
你可以说说你的场景或者你想实现的逻辑，具体一点。

**Comment by YummyLau** [comment]
@jiangsai 你可以说说你的场景或者你想实现的逻辑，具体一点。
