### ISSUE TITLE
耗时任务超过10秒

### ISSUE THREAD

**Issue by jiangsai** [YummyLau/Anchors#31]
耗时某个任务超过10秒，这个框架在某些手机上有问题。
1.启动app，在任务没有完成情况下，手动杀死app。
2.重新启动app，直接崩溃

**Comment by jiangsai** [comment]
作者没有遇到这个问题么

**Comment by YummyLau** [comment]
没遇到过。

**Comment by YummyLau** [comment]
@jiangsai 没遇到过。

**Comment by YummyLau** [comment]
@jiangsai 没遇到过。某些手机可以列一下，日志贴一下。启动app直接奔溃的日志。

**Comment by jiangsai** [comment]
华为的，有qq吗，我加你，我有录视频的，我就改了10秒中

**Comment by YummyLau** [comment]
@jiangsai 主页加我微信吧。
