### ISSUE TITLE
任务分支

### ISSUE THREAD

**Issue by ARabbitCoder** [YummyLau/Anchors#34]
如果有2种场景 ：
taskA--->taskB--->taskC--->taskD--->taskE
taskA--->taskB--->taskC--->taskF--->taskG
能否taskC内根据任务结果进行任务分支切换？类似branchTaskC

**Comment by YummyLau** [comment]
block倒是有类似的场景。
但动态的目前没有，因为依赖链是静态的，可以自定义一个抽象task，触发某个条件之后不再执行也行。

**Comment by LinYYY** [comment]
> 如果有2种场景 ： taskA--->taskB--->taskC--->taskD--->taskE taskA--->taskB--->taskC--->taskF--->taskG 能否taskC内根据任务结果进行任务分支切换？类似branchTaskC

v1.1.6支持在运行时裁剪当前任务的后续任务，具体使用可以参考demo
