### ISSUE TITLE
请问什么场景下会需要在Application.onCreate中必须执行完的任务？

### ISSUE THREAD

**Issue by JackyAndroid** [YummyLau/Anchors#5]

**Comment by JackyAndroid** [comment]
这个库和alpha主要的区别，应该就是在onCreate中可以设置锚点任务。
但有什么样的场景需要有这样一个依赖任务链条在onCreate中必须完成的？

**Comment by YummyLau** [comment]
> 这个库和alpha主要的区别，应该就是在onCreate中可以设置锚点任务。
> 但有什么样的场景需要有这样一个依赖任务链条在onCreate中必须完成的？

我们项目是组件化的，每个组件的依赖相对独立，有部分模块需要在onCreate中初始化，同时，有部分组件的依赖初始化支持在onCreate之前并发，这个库不仅仅支持锚点，也支持同异步任务构成链。

**Comment by JackyAndroid** [comment]
恩了解
