### ISSUE TITLE
demo代码连续调用两次就崩

### ISSUE THREAD

**Issue by hnbc8848** [YummyLau/Anchors#6]
SampleApplication.java
// 这里连续调用两次就崩
new TaskTest().start();
new TaskTest().start();

**Comment by YummyLau** [comment]
> SampleApplication

这里你用错了。
你收到的异常应该是 ：Caused by: java.lang.RuntimeException: Multiple different tasks are not allowed to contain the same id 。
 TaskTest本来就是一棵完整的依赖树。框架在初始化依赖树的时候，每个节点都有一个标志位为唯一，且框架支持同异步节点的依赖链，内部会根据标志进行任务同步初始。连续调用两次没有关系，前提是你要保证每个task都是唯一的。
